Add missing throws to doc blocks
laravel/lumen-framework pull request #1210
Opened 2021-12-28 21:46 UTC by dunhamjared

Added missing throws to doc blocks.

Used `\Symfony\Component\HttpKernel\Exception\HttpException` for exceptions that extend `HttpsException` based on https://github.com/dunhamjared/lumen-framework/blob/8.x/src/Concerns/RegistersExceptionHandlers.php#L18-L35

2021-12-28 21:59 UTC, GrahamCampbell commented
Runtime exceptions should not go in throw doc. All methods throw RuntimeException|Error by default.

2021-12-28 22:14 UTC, dunhamjared commented
@GrahamCampbell 

Found two extra instances of RuntimeException and removed them. 

https://github.com/laravel/lumen-framework/blob/8.x/src/Http/Request.php#L56 - from 3 years ago
https://github.com/laravel/lumen-framework/blob/8.x/src/Application.php#L925 - from 6 years ago

2021-12-29 00:40 UTC, GrahamCampbell requested changes

2021-12-29 00:40 UTC, GrahamCampbell commented on src/Application.php
> -     * @throws \RuntimeException
Please leave this fix to the master branch (if it was not already made there). The additional throw I think are fine for 8.x.

2021-12-29 17:00 UTC, closed without merging

2021-12-29 17:02 UTC, dunhamjared commented
Hi @taylorotwell 

Is there a reason for closing this pull request?